//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUPHAT
    {
        public string MaPhieuPhat { get; set; }
        public string MaPhieuMuon { get; set; }
        public Nullable<System.DateTime> NgayTaoPhieuPhat { get; set; }
        public Nullable<int> TienPhat { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
