//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRA
    {
        public string MaPhieuTra { get; set; }
        public string MaPhieuMuon { get; set; }
        public string MaDocGia { get; set; }
        public string MaSach { get; set; }
        public Nullable<System.DateTime> NgayTaoPhieuTra { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
